# Generated by Django 4.1 on 2022-08-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(help_text='Enter an album', max_length=200),
        ),
    ]
