# Generated by Django 4.1 on 2022-08-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a band or artist', max_length=200, null=True),
        ),
    ]
