# Generated by Django 4.1 on 2022-08-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='None', help_text='Enter a band or artist', max_length=200),
            preserve_default=False,
        ),
    ]
