# Generated by Django 4.1 on 2022-08-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_remove_album_genre_album_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
