# Generated by Django 4.1 on 2022-08-25 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='null', help_text='Enter a title for this image', max_length=200),
            preserve_default=False,
        ),
    ]
