# Generated by Django 4.1 on 2022-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_rename_image_cover_rename_image_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
