# Generated by Django 4.1 on 2022-08-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_alter_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
